config:
  aws:region: us-west-2
  aws:accessKey:
    secure: AAABAEKptBd455WZNIqiCFQ9ql1wBcgLyk6egaKu17qDiHY7JBhVHiNZRTjHkpixVne7WQ==
  aws:secretKey:
    secure: AAABAJc4cuLGHdOcX7bj0klND/d2XQzMrGn1dzLskNKIR3+YuAQ7bkQip0j1pCYX12x9yf/b91pX4SJviwgie60q2alVR6Yi
