config:
  aws:secretKey:
    secure: AAABACR9Jyd4atXEJZLIliXDCapznvKiZCyPbWWgp4Ut78JxrdkgtFnF79o0JCDRDtAR4ixeP9i8eZnhLvPX0Zk5PtZknqTN
  aws:accessKey:
    secure: AAABAMAt8cY/J3ILovPUACUjKOQvQ5BnIFs9tBtUgHdblu8P+j29pxjNkSY2M5WTAX/TiA==
  aws:region: us-west-2
  BaoPun-Website:certificateArn:
    secure: AAABAJqD8QkGGT0Bw2sqTBcVZ2Pgr53V1NzsQYx5cFoXLuu7lGi9H0+wwHKaZ9pb7OkCLtJ2worwXYqBWjhvyH9x9AJ34KygY8n3f68xp4jOuJP/tGjEFGqcWWve5vLtAlZrFh2rU9fG5nTkpBNP/6kodw==
