config:
  aws:secretKey:
    secure: AAABACR9Jyd4atXEJZLIliXDCapznvKiZCyPbWWgp4Ut78JxrdkgtFnF79o0JCDRDtAR4ixeP9i8eZnhLvPX0Zk5PtZknqTN
  aws:accessKey:
    secure: AAABAMAt8cY/J3ILovPUACUjKOQvQ5BnIFs9tBtUgHdblu8P+j29pxjNkSY2M5WTAX/TiA==
  aws:region: us-west-2
  BaoPun-Website:certificationArn:
    secure: AAABAL0WwgbbcUB+pSCqSEdopKfG6J60EQvD+OCIGic6XrIX/tzb8582xKEmlzQsUo+ckyg1dv6uhB8+f3AQCT+ulSaqqI3jh7NPUi0raAeW8aNvygC/bflBwq5LhCQVQIn2opQ85km6lN3OBED7Y5PrCQ==
