---
- name: Deploy Frontend Application with Docker and Nginx (SSL at ALB)
  hosts: baopun-website
  become: yes

  vars:
    frontend_image: "ghcr.io/baopun/baopun-website:latest"
    frontend_container_name: "baopun-website"
    frontend_env:
      NODE_ENV: "production"
    frontend_port: 3000
    nginx_conf_src: "templates/nginx.conf.j2"
    nginx_conf_dest: "/etc/nginx/nginx.conf"

  vars_files:
    - vars/secrets.yml
    - vars/env.yml

  tasks:
    - name: Install required system packages
      yum:
        name:
          - ca-certificates
        state: present
        update_cache: yes

    - name: Install Docker
      yum:
        name:
          - docker
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to GitHub Container Registry
      docker_login:
        registry_url: ghcr.io
        username: "{{ ghcr_username }}"
        password: "{{ ghcr_pat }}"

    - name: Pull frontend container image
      docker_image:
        name: "{{ frontend_image }}"
        source: pull

    - name: Start frontend container
      docker_container:
        name: "{{ frontend_container_name }}"
        image: "{{ frontend_image }}"
        env: "{{ frontend_env }}"
        restart_policy: always
        ports:
          - "{{ frontend_port }}:{{ frontend_port }}"

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Configure Nginx for HTTP only (SSL handled by ALB)
      template:
        src: "{{ nginx_conf_src }}"
        dest: "{{ nginx_conf_dest }}"
        mode: '0644'
      notify: Restart Nginx

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted